name: 'PR'

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'

env:
  NODE_VERSION: '20'

jobs:
  run_tests:
    name: 'Run unit/integration tests'
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1.8.32

      - name: Run tests
        run: npm run test:coverage

  lint:
    name: 'Check for lint issues'
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1.8.32

      - name: build app
        run: npm run lint:ci

  style:
    name: 'Check for style issues'
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1.8.32

      - name: build app
        run: npm run format:ci

  build:
    name: 'Verify the build'
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: bahmutov/npm-install@v1.8.32

      - name: build app
        run: npm run build
